### ISSUE TITLE
Selecting address with Enter submits the form

### ISSUE THREAD

**Issue by iamerikjolson** [wpalahnuk/ngAutocomplete#14]
I love the module - thanks.

I'm using it in a form to collect lots of information. There are many ways to select one of the addresses, but when the user presses the Enter key to select the address the form submits. This results in validation errors for the remaining forms. 

Is there an option so that using the Enter key to select the location will not bubble up to the submitting the form?

**Comment by wpalahnuk** [comment]
Would something like the top answer here work for you:

http://stackoverflow.com/questions/1563062/prevent-form-submission-with-enter-key

There isn't currently an option in the module to disable the enter key from bubbling, but it's something I can look into implementing.

**Comment by iamerikjolson** [comment]
Will,

Thanks for the quick response. That jQuery did the trick. I added the below code to my controller.

```
$("#Autocomplete").keypress(function(e) {
  if (e.which === 13) {
    return false;
  }
});
```

**Comment by DmitryEfimenko** [comment]
I think preventing form submission on pressing Enter makes better UX, so I'd vote on adding this to the directive. It's not hard either. Just add this to the link function:

```
$element.on('keypress', function (e) {
    // prevent form submission on pressing Enter as there could be more inputs to fill out
    if (e.which == 13) {
        e.preventDefault();
    }
});
```

**Comment by monkeymonk** [comment]
+1

If not, what's the point of the options `watchEnter` ??

**Comment by joarhem** [comment]
The "watchEnter" Option from ngAutocomplete enables the option that the fraction you typed in is autocompleted with the first shown option in the dropdown list when pressing enter key. 
Whether you enable watchEnter or not makes no difference for triggered form submission on enter.

The developer just targeted another use case with the watchEnter option i guess.

I lately had the same problem and did some research. I think, that Dmitry's solution is currently the best one. However, It still not feels very comfortable for me to change the directive...

I'd be happy to get informed, when there is a more clean, maybe a module-built-in function for this issue ;)

**Comment by monkeymonk** [comment]
In my case I use this to prevent submit on hitting enter :

```
    // prevent form to be submitted on enter
    google.maps.event.addDomListener($element[0], 'keydown', function (e) {
        if (e.keyCode === 13) {
            e.preventDefault();
        }
    });
```

Hope this help someone! ;-)
