### ISSUE TITLE
Google places autocomplete not working in angular-strap modal

### ISSUE THREAD

**Issue by kpgarrod** [wpalahnuk/ngAutocomplete#21]
I am using this directive happily in a number of places in my app (thank you!), but when I try to use it in a modal, the google results are not shown.

**Comment by pbrain19** [comment]
You have to fix the z-index that is all. Autocomplete plays by its own rules.

**Comment by kpgarrod** [comment]
Thanks. It's probably a stupid question, but z-index of what exactly? I
kinda had an idea that was what I need to do, but wasn't sure what to fix
the z-index of. I would appreciate your help.

On 23 May 2014 05:39, Paul Garcia notifications@github.com wrote:

> You have to fix the z-index that is all. Autocomplete plays by its own
> rules.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/wpalahnuk/ngAutocomplete/issues/21#issuecomment-43968433
> .

## 

Keith Garrod

Tel: +27-83-3000-988
Fax: +27-86-5757781

**Comment by gigablox** [comment]
I'm actually running into this same issue. I set my z-index very, very high but to no avail. Something about absolute positioned elements on top of one another makes this not play nice.

**Comment by pbrain19** [comment]
Any chance this will be solved one day? I got a sample

http://beta.gymbud.co

use mobile phone browser

**Comment by wpalahnuk** [comment]
Hmm, I can't see where you're using the directive in that sample.

**Comment by pbrain19** [comment]
You must sign in using the dummy account I made "pbrain19@gmail.com"  and pass: 321654987p ... then try to make an event... the address field is the autocomplete.

**Comment by leandroz** [comment]
@kpgarrod the problem is with z-index. ngAutocomplete z-index is 1000 and $modal z-index is 1050.
I solve the problem simple with:
.pac-container {
    z-index: 1100 !important;
}

**Comment by kpgarrod** [comment]
@leandroz Thanks!
