### ISSUE TITLE
Not mobile friendly

### ISSUE THREAD

**Issue by pbrain19** [wpalahnuk/ngAutocomplete#22]
I am making an app using your amazing directive. Unfortunetly, it does not click properly when I integrate it with my app. I am using the ionic framework. Here is a sample(use on your phone) . http://shielded-hamlet-4180.herokuapp.com . Please let me know if you plan to support mobile.

**Comment by quanghoc** [comment]
pbrain19, how do you fix this? 

I have exact same problem and `data-tab-disable` = true did not solve it

https://github.com/driftyco/ionic/issues/1798

Also the ion-google-place is using geocoder and not Google Places API so the results are very different (i.e. I don't need to search address for Israel..)

https://github.com/israelidanny/ion-google-place

Any thought?

**Comment by pbrain19** [comment]
I totally forgot what but yes its an easy fix. Will let you know if I come across the fix
