### ISSUE TITLE
Getting LatLng from the autocomplete result

### ISSUE THREAD

**Issue by zacharynevin** [wpalahnuk/ngAutocomplete#3]
Is there a method included that allows me to get the LatLng coordinates from the autocomplete address?

**Comment by intellix** [comment]
Not sure about a method, but basically:

``` html
<input ng-autocomplete type="text" ng-model="autocomplete.query" details="autocomplete.details" options="autocomplete.options">

{{autocomplete.details.geometry.location}}
```

I'm just watching autocomplete.details for change (when it's set) and then using it there in my controller

**Comment by wpalahnuk** [comment]
intellix is correct, that's how you retrieve the latlng.

**Comment by pgAdmin** [comment]
If you want the values separate, then you can use the following methods:

```
{{autocomplete.details.geometry.location.lat()}}
{{autocomplete.details.geometry.location.lng()}}
```

**Comment by surnamename** [comment]
Guys, and how can I use this in controller? 
For example if I need to change input data at autocomplete input on just:
city, state, zip. 

How it could be done? 

Example:
in autocomplete i have: 
Cranberry Township, PA 16066, United States

And need to show in input just: Cranberry Township, PA, 16066,

Thank you for answer!
