### ISSUE TITLE
Add to Bower

### ISSUE THREAD

**Issue by gvn** [wpalahnuk/ngAutocomplete#4]
Can please you tag a release and add to this library to Bower?

**Comment by wpalahnuk** [comment]
Definitely, should be able to get to it this weekend

**Comment by gvn** [comment]
Cool, thanks!

**Comment by wpalahnuk** [comment]
Alright, tagged and added to Bower.

**Comment by gvn** [comment]
Rad!

**Comment by ghost** [comment]
Where is it? I can't find.

**Comment by brunocoelho** [comment]
@mfc-julius here, http://bower.io/search/?q=ngAutocomplete.
