### ISSUE TITLE
Call function in controller with details when select an autocomplete option

### ISSUE THREAD

**Issue by ghost** [wpalahnuk/ngAutocomplete#73]
Does anyone know how to call a function in the controller with details passed as parameter when an option from the autocomplete dropdown is selected?

Thanks

**Comment by robrothedev** [comment]
I ran into the same issue.  I ended up just watching the property from the details attribute in the
ng-autocomplete input and it works pretty well.  

Fiddle Example: http://jsfiddle.net/n3ztwucL/

GitHub Gist: https://gist.github.com/robrothedev/46e1b2a2470b1f8687ad
